spring:
  boot:
    admin:
      client:
        url: http://localhost:9999
  
  kafka:
    bootstrap-servers: localhost:9092
    schema-registry-url: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    tags: 
      application: ${spring.application.name}

kafka:
  topics:
    order: local.distributed-ecommerce.order