version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-buster-node-browsers-legacy
    steps:
      - checkout
      - run: 
          name: java version
          command: |
            java -version
            ls
            cd catalog-service
            ls
      - run: 
          name: java version
          command: |
            ls

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
