version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-buster-node-browsers-legacy
    steps:
      - run: 
          name: catalog-service
          command: |
            cd catalog-service
            mvn clean package
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex "catalog-service/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit 
            
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
