version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test:
        name: catalog-service
        test_results_path: catalog-service/target/surefire-reports
        app_src_directory: catalog-service
      - maven/test:
        name: payment-service
        test_results_path: payment-service/target/surefire-reports
        app_src_directory: payment-service
