spring:
  boot:
    admin:
      client:
        url: http://localhost:9999
        
  datasource:
    url: jdbc:h2:mem:localdb

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always